### ISSUE TITLE
Unpacked Size 1.27 MB

### ISSUE THREAD

**Issue by zenflow** [MJavaadAkhtar/Awesome-text-effects#1]
Looks like a cool little library. First thing that jumped out at me though was the "Unpacked Size" on https://www.npmjs.com/package/awesome-text-effects
(1.27 MB).

There's gotta be something up with that.

**Comment by MJavaadAkhtar** [comment]
The package size is updated, it is now 123 KB. The pictures from README folder were also being uploaded to NPM package causing it to be 1.27MB. More optimization might be done later this week. 

Thank you for raising this issue.

**Comment by zenflow** [comment]
You published another version on npm, but no updates in the git repository? 😦 Ideally users should be able to link the version on npm to a tag on GitHub to see the exact code they're running.
